<article class="article-fw">
								<div class="inner">
									<figure>
										<a href="[field:arcurl/]">
											<img src="[field:litpic/]" alt="[field:title/]">
										</a>
									</figure>
									<div class="details">
										<div class="detail">
											<div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
											<div class="category"><a href="[field:typelink/]">[field:typename/]</a>
											</div>
										</div>
										<h1><a href="[field:arcurl/]">[field:title/]</a></h1>
										<p>
											[field:arcinfo/]
										</p>
									</div>
								</div>
							</article>