<?php
$z[0]=Array("litpic","",129,144);
$z[0][4]=array();
$z[1]=Array("title","",151,165);
$z[1][4]=array();
$z[2]=Array("typelink","",259,276);
$z[2][4]=array();
$z[3]=Array("typename","",278,295);
$z[3][4]=array();
$z[4]=Array("arcurl","",329,344);
$z[4][4]=array();
$z[5]=Array("title","",346,360);
$z[5][4]=array();
$z[6]=Array("pubdate","",398,445);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y-m-d',@me)";

?>