<article class="article related col-md-6 col-sm-6 col-xs-12">
							<div class="inner">
								<figure>
									<a href="[field:arcurl/]">
										<img src="[field:litpic/]">
									</a>
								</figure>
								<div class="padding">
									<h2><a href="[field:arcurl/]">[field:title/]</a></h2>
									<div class="detail">
										<div class="category"><a href="[field:typelink/]">[field:typename/]</a></div>
										<div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
									</div>
								</div>
							</div>
						</article>