<?php
$z[0]=Array("arcurl","",127,142);
$z[0][4]=array();
$z[1]=Array("litpic","",166,181);
$z[1][4]=array();
$z[2]=Array("arcurl","",272,287);
$z[2][4]=array();
$z[3]=Array("title","",289,303);
$z[3][4]=array();
$z[4]=Array("typelink","",386,403);
$z[4][4]=array();
$z[5]=Array("typename","",405,422);
$z[5][4]=array();
$z[6]=Array("pubdate","",462,509);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y-m-d',@me)";

?>