<article class="col-md-12 article-list">
							<div class="inner">
								<figure>
									<a href="[field:arcurl/]">
										<img src="[field:litpic/]" alt="[field:title/]">
									</a>
								</figure>
								<div class="details">
									<div class="detail">
										<div class="category">
											<a href="[field:typelink/]">[field:typename/]</a>
										</div>
										<div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
									</div>
									<h1><a href="[field:arcurl/]">[field:title/]</a></h1>
									<p>
										[field:info/]
									</p>
									<footer>
										<a href="#" class="love"><i class="ion-android-favorite-outline"></i>
											<div>273</div>
										</a>
										<a class="btn btn-primary more" href="[field:arcurl/]">
											<div>More</div>
											<div><i class="ion-ios-arrow-thin-right"></i></div>
										</a>
									</footer>
								</div>
							</div>
						</article>
						
						
					</div>
				</div>
				<div class="col-xs-6 col-md-4 sidebar" id="sidebar">
					<div class="sidebar-title for-tablet">Sidebar</div>
					<aside>
						<div class="aside-body">
							<div class="featured-author">
								<div class="featured-author-inner">
									<div class="featured-author-cover"
										style="background-image: url('images/news/img15.jpg');">
										<div class="badges">
											<div class="badge-item"><i class="ion-star"></i> 广州</div>
										</div>
										<div class="featured-author-center">
											<figure class="featured-author-picture">
												<img src="images/img01.jpg" alt="25℃">
											</figure>
											<div class="featured-author-info">
												<h2 class="name">25℃</h2>
												<div class="desc">舒适</div>
											</div>
										</div>
									</div>
									<div class="featured-author-body">
										<div class="featured-author-count">
											<div class="item">
												<a href="#">
													<div class="name">风向</div>
													<div class="value">东南</div>
												</a>
											</div>
											<div class="item">
												<a href="#">
													<div class="name">风速</div>
													<div class="value">2~3节</div>
												</a>
											</div>
											<div class="item">
												<a href="#">
													<div class="name">湿度</div>
													<div class="value">80%</div>
												</a>
											</div>
										</div>
										<div class="featured-author-quote">
											"test"
										</div>
										<div class="block">
											<h2 class="block-title">Photos</h2>
											<div class="block-body">
												<ul class="item-list-round" data-magnific="gallery">
													<li><a href="images/news/img06.jpg"
															style="background-image: url('images/news/img06.jpg');"></a>
													</li>
													<li><a href="images/news/img07.jpg"
															style="background-image: url('images/news/img07.jpg');"></a>
													</li>
													<li><a href="images/news/img08.jpg"
															style="background-image: url('images/news/img08.jpg');"></a>
													</li>
													<li><a href="images/news/img09.jpg"
															style="background-image: url('images/news/img09.jpg');"></a>
													</li>
													<li><a href="images/news/img10.jpg"
															style="background-image: url('images/news/img10.jpg');"></a>
													</li>
													<li><a href="images/news/img11.jpg"
															style="background-image: url('images/news/img11.jpg');"></a>
													</li>
													<li><a href="images/news/img12.jpg"
															style="background-image: url('images/news/img12.jpg');">
															<div class="more">+2</div>
														</a></li>
													<li class="hidden"><a href="images/news/img13.jpg"
															style="background-image: url('images/news/img13.jpg');"></a>
													</li>
													<li class="hidden"><a href="images/news/img14.jpg"
															style="background-image: url('images/news/img14.jpg');"></a>
													</li>
												</ul>
											</div>
										</div>
										<!-- <div class="featured-author-footer">
											<a href="#">See All Authors</a>
										</div> -->
									</div>
								</div>
							</div>
						</div>
					</aside>
					<aside>
						<h1 class="aside-title">热点新闻 <a href="#" class="all">更多 <i
									class="ion-ios-arrow-right"></i></a></h1>
						<div class="aside-body">
							{dede:arclist typeid=3 flag='f' row='6'}
							<article class="article-mini">
								<div class="inner">
									<figure>
										<a href="[field:arcurl/]">
											<img src="[field:litpic/]" alt="[field:title/]">
										</a>
									</figure>
									<div class="padding">
										<h1><a href="[field:arcurl/]">[field:title/]</a>
										</h1>
									</div>
								</div>
							</article>