<div class="item">
									<div class="user">
										<figure>
											<img src="[field:litpic/]" alt="User Picture">
										</figure>
										<div class="details">
											<h5 class="name">Mark Otto</h5>
											<div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
											<div class="description">
												[field:title/]
											</div>
										</div>
									</div>
								</div>