<?php
$z[0]=Array("field","",50,78);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",80,109);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",165,193);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n              <li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title\r\n                  /]</a></li>\r\n              ",286,501);
$z[3][4]=array();
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>