<article class="featured">
								<div class="overlay"></div>
								<figure>
									<img src="[field:litpic/]" alt="[field:title/]">
								</figure>
								<div class="details">
									<div class="category"><a href="[field:typelink/]">[field:typename/]</a></div>
									<h1><a href="[field:arcurl/]">[field:title/]</a></h1>
									<div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
								</div>
							</article>