<?php
$z[0]=Array("litpic","",102,117);
$z[0][4]=array();
$z[1]=Array("title","",124,138);
$z[1][4]=array();
$z[2]=Array("typelink","",232,249);
$z[2][4]=array();
$z[3]=Array("typename","",251,268);
$z[3][4]=array();
$z[4]=Array("arcurl","",302,317);
$z[4][4]=array();
$z[5]=Array("title","",319,333);
$z[5][4]=array();
$z[6]=Array("pubdate","",371,418);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y-m-d',@me)";

?>