<article class="col-md-12 article-list">
							<div class="inner">
								<figure>
									<a href="[field:arcurl/]">
										<img src="[field:litpic/]" alt="[field:title/]">
									</a>
								</figure>
								<div class="details">
									<div class="detail">
										<div class="category">
											<a href="[field:typelink/]">[field:typename/]</a>
										</div>
										<div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
									</div>
									<h1><a href="[field:arcurl/]">[field:title/]</a></h1>
									<p>
										[field:info/]
									</p>
									<footer>
										<a href="#" class="love"><i class="ion-android-favorite-outline"></i>
											<div>273</div>
										</a>
										<a class="btn btn-primary more" href="[field:arcurl/]">
											<div>More</div>
											<div><i class="ion-ios-arrow-thin-right"></i></div>
										</a>
									</footer>
								</div>
							</div>
						</article>