<article class="article-mini">
								<div class="inner">
									<figure>
										<a href="[field:arcurl/]">
											<img src="[field:litpic/]" alt="[field:title/]">
										</a>
									</figure>
									<div class="padding">
										<h1><a href="[field:arcurl/]">[field:title/]</a></h1>
										<div class="detail">
											<div class="category"><a href="[field:typelink/]">[field:typename/]</a></div>
											<div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
										</div>
									</div>
								</div>
							</article>