
         
          <li class="dropdown magz-dropdown"><a href="[field:typelink/]">[field:typename/] <i class="ion-ios-arrow-right"></i></a>
            <ul class="dropdown-menu">
              <li><a href="category.html">Internet</a></li>
              <li class="dropdown magz-dropdown"><a href="category.html">Troubleshoot <i
                    class="ion-ios-arrow-right"></i></a>
                <ul class="dropdown-menu">
                  <li><a href="category.html">Software</a></li>
                  <li class="dropdown magz-dropdown"><a href="category.html">Hardware <i
                        class="ion-ios-arrow-right"></i></a>
                    <ul class="dropdown-menu">
                      <li><a href="category.html">Main Board</a></li>
                      <li><a href="category.html">RAM</a></li>
                      <li><a href="category.html">Power Supply</a></li>
                    </ul>
                  </li>
                  <li><a href="category.html">Brainware</a>
                </ul>
              </li>
              <li><a href="category.html">Office</a></li>
              <li class="dropdown magz-dropdown"><a href="#">Programming <i class="ion-ios-arrow-right"></i></a>
                <ul class="dropdown-menu">
                  <li><a href="category.html">Web</a></li>
                  <li class="dropdown magz-dropdown"><a href="category.html">Mobile <i
                        class="ion-ios-arrow-right"></i></a>
                    <ul class="dropdown-menu">
                      <li class="dropdown magz-dropdown"><a href="category.html">Hybrid <i
                            class="ion-ios-arrow-right"></i></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Ionic Framework 1</a></li>
                          <li><a href="#">Ionic Framework 2</a></li>
                          <li><a href="#">Ionic Framework 3</a></li>
                          <li><a href="#">Framework 7</a></li>
                        </ul>
                      </li>
                      <li><a href="category.html">Native</a></li>
                    </ul>
                  </li>
                  <li><a href="category.html">Desktop</a></li>
                </ul>
              </li>
            </ul>
          </li>
          