<div class="author">
						<figure>
							<img src="[field:face/]">
						</figure>
						<div class="details">
							<div class="job">Web Developer</div>
							<h3 class="name">[field:uname/]</h3>
							<p>Nulla sagittis rhoncus nisi, vel gravida ante. Nunc lobortis condimentum elit, quis porta
								ipsum rhoncus vitae. Curabitur magna leo, porta vel fringilla gravida, consectetur in
								libero. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.</p>
							<ul class="social trp sm">
								<li>
									<a href="#" class="facebook">
										<svg>
											<rect /></svg>
										<i class="ion-social-facebook"></i>
									</a>
								</li>
								
							</ul>
						</div>
					</div>