<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}'><img src='{@me['litpic']}'/></a>\"); ",97,235);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",372,389);
$z[1][4]=array();
$z[2]=Array("typename","",391,408);
$z[2][4]=array();
$z[3]=Array("pubdate","",460,506);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("arcurl","",553,568);
$z[4][4]=array();
$z[5]=Array("title","",570,584);
$z[5][4]=array();
$z[6]=Array("description","",630,650);
$z[6][4]=array();
$z[7]=Array("click","",786,800);
$z[7][4]=array();
$z[8]=Array("scores","",916,931);
$z[8][4]=array();
$z[9]=Array("arcurl","",1003,1018);
$z[9][4]=array();

?>