<?php
$z[0]=Array("global","",200,226);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("tag","\r\n                <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n                ",923,1062);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['getall']="1";
$z[1][4]['sort']="month";
$z[2]=Array("global","",1252,1278);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmspath";
$z[3]=Array("global","",1442,1468);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("global","",2322,2348);
$z[4][4]=array();
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("global","",2427,2453);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("global","",2540,2565);
$z[6][4]=array();
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("channelartlist","\r\n          <li class=\"dropdown magz-dropdown\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/} <i\r\n                class=\"ion-ios-arrow-right\"></i></a>\r\n            <ul class=\"dropdown-menu\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",2595,3056);
$z[7][4]=array();

?>