<?php
$z[0]=Array("tag","\r\n                <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n                ",907,1046);
$z[0][4]=array();
$z[0][4]['row']="5";
$z[0][4]['getall']="1";
$z[0][4]['sort']="month";
$z[1]=Array("global","",2342,2367);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channelartlist","\r\n          <li class=\"dropdown magz-dropdown\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/} <i\r\n                class=\"ion-ios-arrow-right\"></i></a>\r\n            <ul class=\"dropdown-menu\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",2397,2880);
$z[2][4]=array();
$z[2][4]['typeid']="top";
$z[2][4]['row']="10";

?>